baseurl = "https://gogotattoo.github.io"
languageCode = "en-us"
title = "gogo.tattoo"
googleAnalytics = "UA-79234406-1"

DefaultContentLanguage = "en"

[Languages]
  [Languages.en]
    weight = 1
    title = "gogo.tattoo (Alpha)"
  [Languages.zh]
    weight = 3
    title = "gogo.tattoo (Alpha)"
  [Languages.zh-hant]
    weight = 2
    title = "gogo.tattoo (Alpha)"
  [Languages.ru]
    weight = 2
    title = "gogo.tattoo (Alpha)"
  [Languages.ja]
    weight = 3
    title = "gogo.tattoo (Alpha)"
  [Languages.sv]
    weight = 4
    title = "gogo.tattoo (Alpha)"
  [Languages.es]
    weight = 4
    title = "gogo.tattoo (Alpha)"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "gogo.tattoo"
	description = "main.slogan"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "gogo tattoo  (Alpha)"

		[params.navigation.links]
			about     = "nav.about"
			services  = "nav.services"
			portfolio = "nav.portfolio"
			contact   = "nav.contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "main.slogan"
		subtitle   = "main.subtitle"
		btn        = "main.buttonText"


	# About section
	[params.about]
		headline    = "about.headline"
		subtitle   = "about.subtitle"
		description = "about.description"
		description2 = "about.description2"
		buttonText  = "about.buttonText"


	# Service section
	[params.services]
		headline = "services.headline"

        [[params.services.list]]
            image = "lady1"
            title = "service.item1"
            description = "service.desc1"

        [[params.services.list]]
      			image = "lady2"
      			title = "service.item2"
      			description = "service.desc2"

		[[params.services.list]]
            image = "lady3"
						title = "service.item3"
						description = "service.desc3"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Call to Action section
	[params.cta]
		headline = "cta.headline"
    explanation = "cta.explanation"

		[params.cta.button]
			text = "cta.buttonText"
			link = "//github.com/gogotattoo/"

  [params.maillist]
    headline = "maillist.headline"
    explanation = "maillist.explanation"
    placeholder = "maillist.placeholder"

		[params.maillist.button]
			text = "maillist.buttonText"
			link = "//github.com/gogotattoo/"
	# Contact section
	[params.contact]
		headline = "contact.headline"
		description = "contact.description"
		email = "team@gogo.tattoo"
    slack = "http://gogotattoo.slack.com"
    twitter = "http://twitter.com/gogo_tattoo"
    ryver = "http://gogotattoo.ryver.com"
    steemit = "gogo.tattoo"
