name = "Gogo Tattoo"
license = "Apache License 2.0"
licenselink = "//github.com/gogotattoo/gogo.tattoo/blob/master/LICENSE"
description = "A one page HTML theme for creatives."
homepage = "//github.com/gogotattoo/gogo.tattoo"
tags = ["creative", "portfolio"]
features = ["responsive", "portfolio", "substitutable strings"]
min_version = 0.17

[author]
  name = "roman@gogo.tattoo"
  homepage = "//github.com/gogotattoo"
